object deep assign
nan-academy/js-training pull request #53
Opened 2020-04-22 09:06 UTC by LEEDASILVA

2020-04-27 14:12 UTC, kigiri requested changes
So we talk about it on discord:
- Add more tests
- Make tests more descriptive to what is being tested
- Split in 2 exercises `assignDeep` and `copyDeep`

2020-04-27 14:12 UTC, kigiri commented on exercise/replicate.js
> +const $f = { a: { b: 4, c: { d: { e: 'xau' } } } }
we could add a quote from blade runner:
> Replicants weren't supposed to have feelings... neither were blade runners.
>
> - Rick Deckard

2020-04-27 14:12 UTC, kigiri commented on tests/replicate/fail_JSON.js
> +  JSON.parse(JSON.stringify(Object.assign(target, ...obj)))
I don't think that this tests properly that we didn't use `JSON` to copy as this is still a shalow copy

2020-04-27 14:12 UTC, kigiri commented on tests/replicate/pass_ms.js
> +const replica = (target, ...obj) => copyObject(Object.assign(target, ...obj))
I'm pretty sure I can write a test that makes this fail, i'll give it a shot

2020-04-27 14:57 UTC, LEEDASILVA commented on exercise/replicate.js
> +const $f = { a: { b: 4, c: { d: { e: 'xau' } } } }
ohh ok cool

2020-04-27 23:22 UTC, LEEDASILVA commented on tests/replicate/fail_JSON.js
> +  JSON.parse(JSON.stringify(Object.assign(target, ...obj)))
i did a separated pr with the deep copy and the fail test here https://github.com/nan-academy/js-training/pull/70

2020-04-27 23:24 UTC, LEEDASILVA commented on tests/replicate/pass_ms.js
> +const replica = (target, ...obj) => copyObject(Object.assign(target, ...obj))
yup you are right it fails. I corrected the solution and the subject. But i will update my solution

2020-05-06 17:26 UTC, kigiri approved these changes

2020-05-06 17:34 UTC, merged