object DNA/RNA
nan-academy/js-training pull request #62
Opened 2020-04-22 12:06 UTC by LEEDASILVA

2020-04-22 12:23 UTC, OGordoo commented on exercise/molecules-cells.js
> +Sense both strands are a sequence of nucleotides. It will be given the four nucleotides and its complements
typo: Sense -> Since

2020-04-22 13:57 UTC, LEEDASILVA commented on exercise/molecules-cells.js
> +Sense both strands are a sequence of nucleotides. It will be given the four nucleotides and its complements
thanks :)

2020-04-23 12:21 UTC, kigiri requested changes
recap of the discord discussion:
```
[2:15 PM] clement: the problem I have with it, it's that you don't really have to use objects yeah
[2:15 PM] clement: but the exercise is cool non the less
[2:15 PM] clement: maybe we could use this exercise in the data branch
[2:15 PM] Lee: yha thats the problem, maybe i will think a bit more about that one
[2:15 PM] clement: and make one for object
[2:16 PM] clement: were you give it 2 strings
[2:16 PM] Lee: ok ok
[2:16 PM] clement: and it return a matching object
[2:16 PM] clement: where a[0]: b[0],  a[1]: b[1], ...etc
[2:16 PM] clement: it's a bit more abstract
[2:16 PM] clement: but could work
```

2020-05-07 13:35 UTC, kigiri approved these changes

2020-05-07 13:35 UTC, merged

2020-05-07 13:37 UTC, kigiri approved these changes